RISC-V: add litex_linux_defconfig
Use https://github.com/litex-hub/linux-on-litex-vexriscv-prebuilt/blob/master/build/arty/gateware/top.bit

ARTY BITSTREAM BUILD HOWTO
--------------------------

  $ git clone https://github.com/litex-hub/linux-on-litex-vexriscv
  $ cd linux-on-litex-vexriscv
  $ export PATH=$PATH:/opt/riscv64-unknown-elf-gcc-20171231-x86_64-linux-centos6/bin
  $ export PATH=$PATH:/opt/xilinx/201x.y/Vivado/201x.y/bin
  $ ./make.py --board=arty --build

The FPGA bitstream file
  build/arty/gateware/top.bit
will be generated.

Also will be generated

  buildroot/rv32.dtb
  emulator/emulator.bin
  build/arty/arty.dts
  build/arty/csr.json

LINUX IMAGE BUILD HOWTO
-----------------------

  $ git clone http://github.com/buildroot/buildroot
  $ cd buildroot
  $ make BR2_EXTERNAL=../linux-on-litex-vexriscv/buildroot/ litex_vexriscv_defconfig
  $ make

The linux kernel image and rootfs image will be generated:

  output/images/Image
  output/images/rootfs.cpio

BAREBOX BUILD HOWTO
-------------------

On Debian 10 Linux:

  $ sudo apt-get install -y make gcc flex bison gcc-riscv64-linux-gnu
  $ git clone -b 20200330.litex-vexriscv-linux https://github.com/litex-hub/barebox
  $ cd barebox
  $ make ARCH=riscv litex_linux_defconfig
  $ make ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu-

You can use compiler recommended by litex:

  $ wget https://static.dev.sifive.com/dev-tools/riscv64-unknown-elf-gcc-8.1.0-2019.01.0-x86_64-linux-ubuntu14.tar.gz
  $ tar -xvf riscv64-unknown-elf-gcc-8.1.0-2019.01.0-x86_64-linux-ubuntu14.tar.gz
  $ make ARCH=riscv CROSS_COMPILE=$PWD/riscv64-unknown-elf-gcc-8.1.0-2019.01.0-x86_64-linux-ubuntu14/bin/riscv64-unknown-elf-

As a result barebox.bin file will be obtained.

Copy barebox.bin into boot.bin file in the root directory of your tftp server.

Load bitstream file into board and see this boot log:

--============== Boot ==================--
Booting from serial...
Press Q or ESC to abort boot completely
sL5DdSMmkekro
             Timeout
Booting from network...
Local IP : 192.168.1.50
Remote IP: 192.168.1.100
Fetching from: UDP/69
Unable to download Image over TFTP
Network boot failed
Unable to download Linux images, falling back to boot.bin
Downloaded 291148 bytes from boot.bin over TFTP to 0x40000000
Executing booted program at 0x40000000

--============= Liftoff! ===============--
Switch to console [cs0]

barebox 2020.03.0-00130-gea6b38c673 #1 Sat Apr 4 12:33:58 MSK 2020

Board: LiteX VexRiscV-SoC-Linux
eth0: got preset MAC address: 5c:74:10:44:88:74
mdio_bus: miibus0: probed
liteeth f0004000.mac@f0003800.of: liteeth driver registered
netconsole: registered as netconsole-1
Warning: Using dummy clocksource
malloc space: 0x44100000 -> 0x44ffffff (size 15 MiB)

Hit any to stop autoboot:    0
Booting entry 'net'
eth0: 100Mbps full duplex link detected
could not open /mnt/tftp/none-linux-vexriscv-soc-linux: No such file or directory
ERROR: Booting entry 'net' failed
Nothing bootable found
barebox@LiteX VexRiscV-SoC-Linux:/

RUN LINUX FROM BAREBOX
----------------------

barebox@LiteX VexRiscV-SoC-Linux:/ ifup eth0
barebox@LiteX VexRiscV-SoC-Linux:/ tftp Image
        [#################################################################]
barebox@LiteX VexRiscV-SoC-Linux:/ tftp rv32.dtb
        [#################################################################]
barebox@LiteX VexRiscV-SoC-Linux:/ tftp rootfs.cpio
        [#################################################################]
barebox@LiteX VexRiscV-SoC-Linux:/ tftp emulator.bin
        [#################################################################]
barebox@LiteX VexRiscV-SoC-Linux:/ memcpy -s Image 0 0x40000000
barebox@LiteX VexRiscV-SoC-Linux:/ memcpy -s rootfs.cpio 0 0x40800000
barebox@LiteX VexRiscV-SoC-Linux:/ memcpy -s rv32.dtb 0 0x41000000
barebox@LiteX VexRiscV-SoC-Linux:/ memcpy -s emulator.bin 0 0x41100000
barebox@LiteX VexRiscV-SoC-Linux:/ go 0x41100000
VexRiscv Machine Mode software built Apr  4 2020 10:52:18
--========== Booting Linux =============--
[    0.000000] Linux version 5.6.0-00008-gfe60ff912578-dirty (antony@buildhost)
(gcc version 9.2.1 20200203 (Debian 9.2.1-28)) #6 Sat Apr 4 01:33:45 MSK 2020

Signed-off-by: Antony Pavlov <antonynpavlov@gmail.com>